name: Setup
description: Sets up the workspace

inputs:
  root:
    description: Where the package files are located
    default: ""
    required: false

runs:
  using: composite
  steps:

    - uses: actions/checkout@v4
      with:
        ref: ${{ inputs.branch }}
        path: ${{ inputs.root }}

    - uses: pnpm/action-setup@v4
      with:
        package_json_file: ${{ inputs.root }}/package.json

    - uses: actions/setup-node@v4
      with:
        cache: "pnpm"
        cache-dependency-path: ${{ inputs.root }}/pnpm-lock.yaml

    - run: pnpm install --frozen-lockfile
      working-directory: base
 
    - run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
