project_id_env: CROWDIN_PROJECT_ID
api_token_env: CROWDIN_API_TOKEN
preserve_hierarchy: 1
files:
  - source: stuff/lang/values/base/*.json
    translation: stuff/lang/values/%osx_locale%/%original_file_name%
