name: Sync Crowdin

on:
  push:
    branches:
      - main
    paths:
      - stuff/lang/values/base/*
      - .github/workflows/crowdin.yml
  schedule:
    - cron: "59 16 * * 6" # “At 16:59 on Saturday.”
  workflow_dispatch:

jobs:
  sync-crowdin:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          path: main

      - name: Crowdin
        uses: crowdin/github-action@1.16.1
        with:
          config: crowdin.yml
          upload_translations: true
          download_translations: true
          push_translations: true
          create_pull_request: false
          localization_branch_name: i18n
          commit_message: "chore(i18n): sync translations"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CROWDIN_PROJECT_ID: ${{ secrets.CROWDIN_ID }}
          CROWDIN_PERSONAL_TOKEN: ${{ secrets.CROWDIN_TOKEN }}

      - name: Pull i18n
        uses: actions/checkout@v4
        with:
          ref: i18n
          path: i18n

      - name: Write files
        run: node /main/.github/scripts/crowdin.mjs
        working-directory: i18n/stuff/lang/values

      - name: Publish changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"

          git add stuff/lang/values/*.json

          git checkout -b test

          git commit -m "chore(i18n): sync translations" || true

          git push
