name: Deploy main branch

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  ci:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: setup workspace
        uses: ./.github/actions/setup

      - name: lint
        run: pnpm lint

      - name: format
        run: pnpm lint

      - name: typecheck
        run: tsc --noEmit

      - name: checkout
        # todo: only run this if "git status -z" is empty
        run: |
          git add .
          git commit -m "chore: run ci" || true
          git pull --ff-only
          git push
  build:
    needs: ci

    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: setup workspace
        uses: ./.github/actions/setup

      - name: build plugins
        run: pnpm build

      - name: copy readme and assets
        run: |
          cp README.md dist/index.md
          cp -r assets dist/assets

      - name: build pages
        uses: actions/jekyll-build-pages@v1
        with:
          source: dist
          destination: built

      - name: upload pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: built
  deploy:
    needs: build

    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: test
        run: |
          echo Hello, World!
          ls
