name: Sync main to dev

on:
  push:
    branches:
      - main

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Git
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'

      - name: Fetch dev branch
        run: git fetch origin dev

      - name: Rebase main branch
        run: git rebase origin/dev
      
      - name: Push changes to dev
        run: git push origin dev