name: Make readmes

on:
  push:
    branches: [main]
    paths:
      - .github/workflows/readmes.yml
      - scripts/readmes.mjs
      - plugins/*/manifest.json
      - plugins/*/status.toml
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  readmes:
    name: Make readmes

    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v3

      - uses: actions/setup-node@v4
        with:
          node-version: "21"
          cache: "pnpm"

      - run: pnpm install --frozen-lockfile

      - name: Write READMEs
        run: node ./scripts/readmes.mjs

      - name: Publish changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"

          git add plugins/*/README.md README.md -f

          git commit -m "style(readmes): update readmes (${{ github.sha || github.triggering_actor }})" || true

          git pull
          git push
