name: Make readmes

on:
  push:
    branches: [main]

jobs:
  readmes:
    name: Make readmes

    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v3

      - name: Prepare environment
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - run: npm install --global yarn

      - name: Install deps
        run: yarn add smol-toml

      - name: Write readmes
        run: node ./readmes.mjs

      - name: Publish changes
        env:
          commit_message: "style(readmes): update readmes"
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add plugins/**/README.md README.md -f
          git commit -m "${{ env.commit_message }}" || true
          git push
